#!/bin/sh

# SPDX-License-Identifier: MPL-2.0
# Copyright (c) 2020-2025 Firas Khana

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.

for i in $(seq 30 37) $(seq 40 48); do
  for j in $(seq 0 9); do
    printf "\033[$j;${i}m\\\033[$j;${i}m\033[0m "
  done

  echo
done
